#!/bin/bash

_test() {
  target=$1
  yasm -f elf64 -o test/${target}.o test/${target}.s
  ld -o test/$target test/${target}.o
  test/$target
  echo
  echo   $?
}

clean() {
  for fname in `find ./test | egrep '\.o$|\.test$|\.l$'`; do
    rm $fname
  done
}

case $1 in
  test) _test $2 ;;
  clean) clean ;; 
esac