#!/bin/sh

set -e

buildlib() {

  # create and/or clean build dir
  mkdir -p lib/build
  rm -f lib/build/*

  # build tests
  for src in lib/test/*.test.s ; do
    obj=lib/build/`basename $src .s`.o
    nasm -i lib/src -f elf64 -g -F dwarf -o $obj $src
    ld -o ${obj%.o} $obj
    rm $obj
  done
}

testlib() {
  for bin in lib/build/*.test ; do
    output=`$bin`
    echo `[ $? -eq 0 ] && echo passed  || echo failed`: $bin
  done
}

case $1 in
  buildlib) buildlib ;;
  testlib) testlib ;;
esac